# Generated by Django 4.2.7 on 2025-12-10 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_exam_assigned_to_alter_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Exam duration in minutes'),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_score',
            field=models.FloatField(default=60.0, help_text='Minimum score to pass (%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
