# Generated by Django 4.2.7 on 2025-12-10 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_exam_duration_minutes_exam_pass_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='institution',
            field=models.CharField(blank=True, help_text='Institution name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, help_text='Full name on certificate', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.FloatField(blank=True, help_text='Score achieved', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
