# Generated by Django 4.2.7 on 2025-12-11 06:03

from django.db import migrations, models
import uuid


def generate_certificate_ids(apps, schema_editor):
    CustomUser = apps.get_model('restapi', 'CustomUser')
    for user in CustomUser.objects.all():
        # Generate a unique 8-character ID
        user.certificate_id = str(uuid.uuid4())[:8].upper()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_certificate_institution_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='Unique user ID for certificates', max_length=20),
        ),
        migrations.RunPython(generate_certificate_ids),
        migrations.AlterField(
            model_name='customuser',
            name='certificate_id',
            field=models.CharField(blank=True, help_text='Unique user ID for certificates', max_length=20, unique=True),
        ),
    ]
