# Generated by Django 5.2.9 on 2025-12-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_alter_useractivitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='restapi.task'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='restapi.exam'),
        ),
    ]
